### ISSUE TITLE
Plan for update the examples for fluxible 0.4.x?

### ISSUE THREAD

**Issue by gilbertwyw** [yahoo/flux-examples#137]
i edited the following in "package.json":
```
"fluxible": "^0.4.0",
```
and continued as described in README.

However, i got the following error: 
```
WARNING in ./~/fluxible/~/es6-promise/dist/es6-promise.js
Module not found: Error: Cannot resolve module 'vertx' in /Users/gilbertwong/dev/gh/flux-examples/node_modules/fluxible/node_modules/es6-promise/dist
 @ ./~/fluxible/~/es6-promise/dist/es6-promise.js 125:20-30
require('fluxible').FluxibleMixin has been moved out of the default exports for Fluxible. Please use require('fluxible/addons/FluxibleMixin') instead.
/Users/gilbertwong/dev/gh/flux-examples/node_modules/fluxible/addons/FluxibleMixin.js:88
            storeInstance = context.getStore(store);
                                    ^
TypeError: undefined is not a function
    at [object Object].FluxibleMixin.getStore (/Users/gilbertwong/dev/gh/flux-examples/node_modules/fluxible/addons/FluxibleMixin.js:88:37)
    at [object Object].getInitialState (/Users/gilbertwong/dev/gh/flux-examples/react-router/components/Timestamp.jsx:17:21)
    at new Constructor (/Users/gilbertwong/dev/gh/flux-examples/node_modules/react/lib/ReactClass.js:853:54)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/gilbertwong/dev/gh/flux-examples/node_modules/react/lib/ReactCompositeComponent.js:135:16)
    at [object Object].wrapper [as mountComponent] (/Users/gilbertwong/dev/gh/flux-examples/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/gilbertwong/dev/gh/flux-examples/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/gilbertwong/dev/gh/flux-examples/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/gilbertwong/dev/gh/flux-examples/node_modules/react/lib/ReactDOMComponent.js:287:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/gilbertwong/dev/gh/flux-examples/node_modules/react/lib/ReactDOMComponent.js:197:12)
    at Object.ReactReconciler.mountComponent (/Users/gilbertwong/dev/gh/flux-examples/node_modules/react/lib/ReactReconciler.js:38:35)
```

**Comment by cesarandreu** [comment]
The vertex warning is happening because of [this](https://github.com/jakearchibald/es6-promise/issues/100).

They have a suggestion in that post, you can add the following to the webpack config in the meantime:

```js
plugins: [
    new webpack.IgnorePlugin(/vertx/),
],
```

**Comment by mridgway** [comment]
Yes, we have a PR open [here](https://github.com/yahoo/flux-examples/pull/119) that will upgrade Fluxible to 0.4.x among other things. We're hoping to merge in the next few days.

**Comment by gilbertwyw** [comment]
:+1:

**Comment by redonkulus** [comment]
Closing this in favor of the PR mentioned above.
