### ISSUE TITLE
Update to Fluxible 0.4

### ISSUE THREAD

**Issue by nicolashery** [yahoo/flux-examples#138]
Specifically interested in the `react-router` example, as I am trying to update my own repo, with no luck so far (https://github.com/nicolashery/example-isomorphic-one/pull/2).

I tried running the `react-router` example after installing latest Fluxible 0.4.3, but getting a runtime error:

```
/Users/nicolashery/Projects/flux-examples/node_modules/fluxible/addons/FluxibleMixin.js:88
            storeInstance = context.getStore(store);
                                    ^
TypeError: undefined is not a function
    at [object Object].FluxibleMixin.getStore (/Users/nicolashery/Projects/flux-examples/node_modules/fluxible/addons/FluxibleMixin.js:88:37)
    at [object Object].getInitialState (/Users/nicolashery/Projects/flux-examples/react-router/components/Timestamp.jsx:17:21)
    at new Constructor (/Users/nicolashery/Projects/flux-examples/node_modules/react/lib/ReactClass.js:853:54)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/nicolashery/Projects/flux-examples/node_modules/react/lib/ReactCompositeComponent.js:135:16)
    at [object Object].wrapper [as mountComponent] (/Users/nicolashery/Projects/flux-examples/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/nicolashery/Projects/flux-examples/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/nicolashery/Projects/flux-examples/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/nicolashery/Projects/flux-examples/node_modules/react/lib/ReactDOMComponent.js:287:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/nicolashery/Projects/flux-examples/node_modules/react/lib/ReactDOMComponent.js:197:12)
    at Object.ReactReconciler.mountComponent (/Users/nicolashery/Projects/flux-examples/node_modules/react/lib/ReactReconciler.js:38:35)
```

I've gotten this in my own repo as well, trying to upgrade.

A little confused because I don't see any breaking changes from `0.3` to `0.4` that could be causing this: https://github.com/yahoo/fluxible/blob/master/CHANGELOG.md#040.

I'm sure I'm missing something, so any help or hints where to look would be appreciated. Thanks! :)

**Comment by mridgway** [comment]
Hi @nicolashery can you try looking at the changes in https://github.com/yahoo/flux-examples/pull/136 to see if it helps you? I haven't tried react-router with 0.4.x yet.

**Comment by nicolashery** [comment]
Thank you @mridgway, this helped a lot! The trick was to use `FluxibleComponent` to wrap React Router's `Handler`, as mentioned in the link you provided (more info on my upgrade here https://github.com/nicolashery/example-isomorphic-one/pull/2).
